runtime: custom
env: flex

service: cicd

instance_class: F4

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

handlers:
  - url: /.*
    script: auto
    secure: always
#network:
#forwarded_ports:
#- 3000/tcp
